#!/bin/bash
# GitHub Actions Status Checker
# Usage: ./check-ci-status.sh

echo "🚀 GitHub Actions CI/CD Pipeline Status"
echo "========================================"
echo ""
echo "📋 Available Workflows:"
echo "  1. Unit Tests - Runs on every push/PR"
echo "  2. CI/CD Pipeline - Comprehensive testing and quality checks"
echo "  3. Dependency Check - Weekly security vulnerability scan"
echo "  4. Release - Automated release on version tags"
echo ""
echo "🔗 Links to monitor workflows:"
echo "  • Actions Page: https://github.com/BINAR-Learning/todo-list-fastapi/actions"
echo "  • Unit Tests: https://github.com/BINAR-Learning/todo-list-fastapi/actions/workflows/test.yml"
echo "  • CI/CD Pipeline: https://github.com/BINAR-Learning/todo-list-fastapi/actions/workflows/ci-cd.yml"
echo ""
echo "📊 Status Badges (add to README.md):"
echo "  ![Unit Tests](https://github.com/BINAR-Learning/todo-list-fastapi/workflows/Unit%20Tests/badge.svg)"
echo "  ![CI/CD Pipeline](https://github.com/BINAR-Learning/todo-list-fastapi/workflows/CI/CD%20Pipeline/badge.svg)"
echo ""
echo "⚡ Quick local testing commands:"
echo "  pytest --cov=app --cov-fail-under=90  # Run tests with coverage"
echo "  flake8 app --max-line-length=127      # Code linting"
echo "  pip install -r requirements-dev.txt  # Install dev tools"
echo ""
echo "✅ Latest Fixes Applied:"
echo "  • Fixed pytest-asyncio compatibility (pytest 7.4.4 + pytest-asyncio 0.21.1)"
echo "  • Updated email-validator to non-yanked version (2.2.0)"
echo "  • Resolved Python version matrix issues with proper quoting"
echo "  • Updated all GitHub Actions to latest stable versions"
echo "  • 91% test coverage achieved locally"
echo ""
echo "🎯 Expected Results:"
echo "  ✅ All workflows should pass without internal errors"
echo "  ✅ Unit tests run successfully on Python 3.9-3.12"
echo "  ✅ No more pytest-asyncio AttributeError issues"
echo "  ✅ No deprecation warnings from outdated actions"
echo ""
echo "📚 For troubleshooting details, see: GITHUB_ACTIONS_FIXES.md"
