@echo off
echo Starting Todo List API Development Server...
echo.
echo Installing dependencies...
pip install -r requirements.txt
echo.
echo Starting FastAPI server...
uvicorn app.main:app --reload --host 0.0.0.0 --port 3000
